-- MySQL Script generated by MySQL Workbench
-- Sat May 18 22:44:46 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Product` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `barcode` INT NOT NULL,
  `store` VARCHAR(255) NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `grade` VARCHAR(1) NOT NULL,
  `category` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Store` (
  `Store_id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Store_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product_Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Product_Category` (
  `Product_id` INT NOT NULL,
  `Category_id` INT NOT NULL,
  PRIMARY KEY (`Product_id`, `Category_id`),
  INDEX `fk_Product_has_Category_Category1_idx` (`Category_id` ASC) VISIBLE,
  INDEX `fk_Product_has_Category_Product_idx` (`Product_id` ASC) VISIBLE,
  CONSTRAINT `fk_Product_has_Category_Product`
    FOREIGN KEY (`Product_id`)
    REFERENCES `Product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_has_Category_Category1`
    FOREIGN KEY (`Category_id`)
    REFERENCES `Category` (`Category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Product_Store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Product_Store` (
  `Product_id` INT NOT NULL,
  `Store_id` INT NOT NULL,
  PRIMARY KEY (`Product_id`, `Store_id`),
  INDEX `fk_Product_has_Store_Store1_idx` (`Store_id` ASC) VISIBLE,
  INDEX `fk_Product_has_Store_Product1_idx` (`Product_id` ASC) VISIBLE,
  CONSTRAINT `fk_Product_has_Store_Product1`
    FOREIGN KEY (`Product_id`)
    REFERENCES `Product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_has_Store_Store1`
    FOREIGN KEY (`Store_id`)
    REFERENCES `Store` (`Store_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Favoris`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Favorite` (
  `substitute_product_id` INT NOT NULL,
  `substituted_product_id` INT NOT NULL,
  PRIMARY KEY (`substitute_product_id`, `substituted_product_id`),
  INDEX `fk_Product_has_Product_Product2_idx` (`substituted_product_id` ASC) VISIBLE,
  INDEX `fk_Product_has_Product_Product1_idx` (`substitute_product_id` ASC) VISIBLE,
  CONSTRAINT `fk_Product_has_Product_Product1`
    FOREIGN KEY (`substitute_product_id`)
    REFERENCES `Product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_has_Product_Product2`
    FOREIGN KEY (`substituted_product_id`)
    REFERENCES `mydb`.`Product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
